### ISSUE TITLE
Sampling in a documentable way

### ISSUE THREAD

**Issue by cfoster0** [mhtess/corpus_generics#9]
Currently, there is no straightforward way of sampling from our corpora, or documentation thereof.

**Comment by mhtess** [comment]
Seems that there are two cases:

- Pilot: We want to sample a small set (e.g., 30 cases) to show to all of our participants.
- Main experiment: We want to sample small sets to show different participants, because we have so many cases that individuals can't see them all.

For the pilot, it's a one-time deal, and we can just do that in R and save the output.
For the main experiment, we can do subsampling in JavaScript.
